### PR TITLE
Improve ThreadedSocketService::new

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
It'll have a conflict with #301 but I'll update once #301 is merged.

cc @sdroege @EPashkin

### CODE REVIEW

**Comment by EPashkin** [comment]
👍

**Comment by sdroege** [comment]
@GuillaumeGomez 

```
error[E0433]: failed to resolve: use of undeclared type or module `SocketService`
 --> src\threaded_socket_service.rs:7:13
  |
7 |             SocketService::from_glib_full(gio_sys::g_threaded_socket_service_new(max_threads))
  |             ^^^^^^^^^^^^^ use of undeclared type or module `SocketService`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0433`.
```

**Comment by GuillaumeGomez** [comment]
Updated!
